### ISSUE TITLE
General Time-lab development discussion.

### ISSUE THREAD

**Issue by ZDDM** [ZDDM/Time-lab#1]
Thread for our to-do list, discussing ideas, talking about lore, etc. 

To-Do list:
- Better HUD. Improving HUD's code. **<- Important**
- Inventory for humans. **<- Important**
- Death. **<- Important**
- Minigames for dead people.
- System that handles minigames in its own Z-level.
- Animations.
-  System that handles events.
-  Pre-round hub. **<- Important**
- Different jobs/kind of scientists.
- Weapons.
- Guns.
- Healing. (Maybe using bandages or something similar?)
- Improving elevators.
- Better lava.
- Substance / Liquid / Chemicals system?
- Map restart without restarting the entire game. (For the "time loops")
- Forcing "time loops".

**Comment by ZackUnfair** [comment]
It would be best if you wrote here what you have in mind, at least the general things so we know what to do, pfft.

**Comment by ZDDM** [comment]
Is this any better? I wrote some kind of to-do list.
I think we should focus on the HUG, getting an inventory done and death.

**Comment by ZDDM** [comment]
When people die, they won't be able to spectate the round as they could know beforehand the events in the lab.
Dead players will probably be sent to some kind of "minigame heaven" until they can take another role. (Example event that requires dead players: Alien invasion.)

**Comment by ZackUnfair** [comment]
I assume we want the inventory to be like SS13's, right? In that case we'll need to work on the HUD first, it will probably require a bit of work.

**Comment by ZDDM** [comment]
After researching some technologies, engineers should be able to build a device that sends messages "back in time".
If everything goes wrong, scientists should be able to send data back in time. (Research data, messages warning about events, etc?)
Also to get messages from the future you would require to build a special machine for it. (If you build it on the first round, you should receive random data that, with enough deciphering, should have info about future events)

**Comment by ZDDM** [comment]
New intention: Interact with object.
If you're holding any objects in your hands, you should be able to interact with certain machines/etc using that object.

**Comment by ZDDM** [comment]
Events have been implemented, however... We need to think different kind of events to make rounds fun and different each time.

**Comment by ZDDM** [comment]
Keys! Keys that can look certain doors so only authorized (or people with stolen keys...) can enter. Humans should have a special slot for keychains.

**Comment by ZDDM** [comment]
Maybe we should try to focus on creating some items and machines?
I'll write some ideas for it later on this post.

**Comment by ZDDM** [comment]
Closing this since now we use Discord.
