### ISSUE TITLE
The Problematic Sanctuary

### ISSUE THREAD

**Issue by Valander** [ZDDM/Time-lab#2]
I'll be using this topic to put up anything bad in a game way in some sort of list. Those are taken from the experimental branch.

So, for now, let's see this list to see what's down.

------------------------

**+Permanent Elevator lights:** Elevator lights will work under any condition, including broken.
**+Door undetection/camouflage:** A character standing in a doorway will not change the door's behaviour. It will close on the character, and hide them behind the door icon. I mean, I know doors still are in progress, but I put it there so we still remember them.

------------------------

Alright, so. Feel free to remove/add your own bugs to the list. Let's do it like this.
"**+Cockroach:** (Desc)" for adding.
"**-Name**" for removing.
Let's say one of these above things is solved. You'll want to write "**-Elevator break**". This way, track could be kept amongst the problems that could arise as things are added.
I will also edit the above list as things are added/removed.

Anyway, that's the one for now. Let's track down and eradicate all these pesky little bugs.

**Comment by ZDDM** [comment]
"Those multiple light bulbs in one" can easily be solved by either changing the behaviour of the elevators (only moving mobs) or by changing the map (making all elevators except the default one completely empty)
What do you think I should do?

**Comment by Valander** [comment]
It depends what you would mean by "moving mobs". Are the lights made as mobs?

**Comment by ZDDM** [comment]
...Nope, they're made as objects. As of right now, the elevator teleports EVERYTHING inside it to upper Z-levels with same x and y coordinates. I could fix the bug by editing the map or by changing the code.

**Comment by ZackUnfair** [comment]
-Blank messages
Spamming and sending blank messages should be fixed now.

**Comment by Valander** [comment]
**+Door replication:** An elevator door can be replicated on its tile if it doesn't manage to close before the elevator changes floor. The door will be replicated on the floor the elevator moved to before the door closes down.

So I guess the 3 bulbs are basically the three floors of the elevator, hmm. I guess maybe something in the code could do it? Like, putting an empty space where the elevator isn't? Would do if someone was to eventually manage to open doors.

**Comment by ZDDM** [comment]
**-Door replication
-Multiple lightbulbs in one**

**Comment by Valander** [comment]
**+Televator:** When changing floors, everything in the elevator will be sent into the bottom left corner wall, in the exception of characters as they can't phase through walls.
**+Intent sprite transparency:** The center of the intent sprites are transparent, which allows one to click through the button. May impede quick intent changes in case of emergencies by quick-clicking into the transparent area. Now this one is less of a bug, more of a practical issue.

Introducing new character: **>Nameofthing:**. I will use this as an update to existing problems.

**>Elevator Break:** The elevator now behaves differently when sent to unexisting floors. When reaching an unexisting floor, the elevator will become dark, wall corners will disapear. It might also be reinforced by Televator sending everything on a corner wall to make them disappear, rendering the elevator unusable.

**Comment by ZDDM** [comment]
-Elevator Break

**Comment by ZackUnfair** [comment]
-**Intent sprite transparency**

**Comment by Valander** [comment]
**+Multi-Hands:** Dropping items will not take your active hand in account. I added one more object through Dream Maker to test this thoroughly to notice that it seems to prioritize dropping what is on your left hand. It was also possible for me to pick up two objects with the same active hand.

**Comment by ZackUnfair** [comment]
-Multi-Hands(sort of):
I fixed being able to hold more than one item in a hand, but dropping things will have to stay the way it is for now, since it's not really a bug, it's just that the inventory is not completed yet so it's more like a feature that will be upgraded.

**Comment by ZDDM** [comment]
This has become obsolete as of commit b0c1567.
